### ISSUE TITLE
Bootstrap algorithm implementation

### ISSUE THREAD

**Issue by open-source-modelling** [qnity/insurance_solidity#1]
Because the libraries are not as developed in Solidity, we should start with a simple bootstrap algorithm and build the library from there.

**Comment by GregorFabjan** [comment]
Implementation uploaded. Still needs testing and documentation

**Comment by GregorFabjan** [comment]
Skeleton of the README file uploaded

**Comment by GregorFabjan** [comment]
README deployed.
